# Generated by Django 4.1.3 on 2022-12-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='newsCategory',
            field=models.CharField(default='uncategorised', max_length=25),
        ),
    ]
