# Generated by Django 4.1.3 on 2022-12-17 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_category_description_newsstory_newscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='newsCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
    ]
