# Generated by Django 4.1.3 on 2022-12-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_newsstory_newscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
